### ISSUE TITLE
cnn error 100%

### ISSUE THREAD

**Issue by DilaraAlbayrak** [ksloke/textrecog#2]
Hi, when i run the test code, i got cnn error 100% and accuracy as 0%, what might be the cause for that?

**Comment by ksloke** [comment]
You need to run 6c2_1 code first at it is doing the training. The test code
reads in the weights created in the training code.
Regards,
Loke KS, Ph.D.: Better Living Through Algorithms

**Comment by DilaraAlbayrak** [comment]
Thanks for your quick reply. Yes, i have already do the training, i have .h5 file. I guess, I see why error is 100%, mainly because test texture's labels are random. The code gives zero score if the random label does not match the original label (the label that cnn guesses). Is there any way that i can get any test image's predicted label(s) rather than its score?

**Comment by ksloke** [comment]
The labels are part of the image file name. I forgot the exact format, as I
don't have access to the files at the moment.
Regards,
Loke KS, Ph.D.: Better Living Through Algorithms

**Comment by ksloke** [comment]
Ok I remember now. The input image is one large image that has the class
label as name. The code extracts 100x100 square from that image and input
it automatically to the training code.
Regards,
Loke KS, Ph.D.: Better Living Through Algorithms

**Comment by DilaraAlbayrak** [comment]
To be clear, i am not asking about the format. Test labels are already written in .h5 file correctly with the corresponding data. While testing, i have randomly named test files (i.e. 1.png, 2.png, etc), as you said. 

The testing yields me scores in a way that if 1.png's actual labels also be `1` (according to training) score of 100% where as if `1` is not the correct label score of 0%. Then, total accuracy/error is calculated based on these boolean scores (100% or 0%) of all test images. What i ask is, is it possible for the model gives me the most similar labels for 1.png are (let's say) 3,4,5,etc. rather than score of 100% or 0%?.

Thanks in advance.

**Comment by ksloke** [comment]
You can use model.predict(x_test) to see what the model is predicting

Regards,
Loke KS, Ph.D.: Better Living Through Algorithms

**Comment by DilaraAlbayrak** [comment]
Thanks.
